# =================================================================
# FILE: apps/docs/book.toml
# This is the final, correct, and minimal configuration.
# It uses the default mdBook theme and will resolve the error.
# =================================================================
[book]
title = "Noda Turbo Project Documentation"
authors = ["The Noda Turbo Team"]
description = "Comprehensive technical documentation for the Noda Turbo project."
language = "en"